export default {
  "SwitchLang": ["Switch English", "切换中文"],
  "cancel": ["取消", "Cancel"],
  "save": ["保存", "Save"],
  "add": ["添加", "Add"],
  "append": ["附加", "Append"],
  "delete": ["删除", "Delete"],
  "empty": ["清空", "Empty"],
  "login": ["登录", "Login"],
  "logout": ["退出", "Logout"],
  "account": ["账号", "Account"],
  "password": ["密码", "Password"],
  "print": ["打印", "Print"],
  "forward": ["转发", "Forward"],
  "reply": ["回复", "Reply"],
  "reply all": ["全部回复", "Reply All"],
  "send": ["发送", "Send"],
  "view": ["查看", "View"],
  "title": ["标题", "title"],
  "content": ["内容", "content"],
  "attachments": ["附件", "attachments"],
  "add data": ["新增数据", "Add Data"],
  "edit data": ["编辑数据", "Edit Data"],
  "verify data": ["审核数据", "Verify Data"],
  "setting-mail": ["消息配置", "Message Setting"],
  "setting-dataflow": ["流程配置", "Process Setting"],
  "_T0000": ["操作成功，{0}行受影响", "Operation succeeded, {0} lines is affected"],
  "_T0001": ["账号或密码不正确", "Incorrect account or password"],
  "_T0002": ["您的IP：{0}未绑定账号：{1}，请联系管理员", "Your IP: {0} unbound account: {1}, Please contact the administrator"],
  "_T0003": ["{0}不允许为空", "{0} can not be empty"],
  "_T0004": ["{0}数字不合法", "{0} Illegal number"],
  "_T0005": ["请输入有效的{0}，它的范围是：{1} - {2}", "Please enter a valid {0} in the following range: {1} - {2}"],
  "_T0006": ["{0}最小长度：{1}，最大长度：{2}", "{0} min length: {1}, max length: {2}"],
  "_T0007": ["无效的命令：{0}", "Invalid command: {0}"],
  "_T0008": ["只有数值类型的字段才能求和", "Only fields of numeric type can be summed"],
  "_T0009": ["表达式包含非法字符：{0}", "The expression contains illegal characters: {0}"],
  "_T0010": ["总计{0}条，最多展示{1}条", "Total {0} items, display {1} items at most"],
  "_T0011": ["删除成功", "Delete succeeded"],
  "_T0012": ["字段【{0}】是必填项", "Column [{0}] is required"],
  "_T0013": ["字段【{0}】在数据库中不存在", "The column [{0}] does not exist in the database"],
  "_T0014": ["总计{0}条，最多导出{1}条", "Total {0} items, export {1} items at most"],
  "_T0015": ["保存成功", "Save Successfully"],
  "_T0016": ["保存成功，更新{0}条，新增{1}条", "Save successfully, update {0} and add {1}"],
  "_T0017": ["基础权限不可更改，请添加新的权限", "Basic perm cannot be changed, Please add new perm"],
  "_T0018": ["发送成功", "Send successfully"],
  "_T0019": ["消息", "Message"],
  "_T0020": ["确定", "Confirm"],
  "_T0021": ["错误代码：{0}", "Error Code: {0}"],
  "_T0022": ["暂无权限", "No Permission"],
  "_T0023": ["提示", "Prompt"],
  "_T0024": ["系统需要刷新浏览器", "The system needs to refresh the browser"],
  "_T0025": ["稍后手动刷新", "Refresh manually later"],
  "_T0026": ["刷新", "Refresh"],
  "_T0027": ["{0}天前", "{0} days ago"],
  "_T0028": ["{0}天后", "{0} days later"],
  "_T0029": ["{0}小时前", "{0} hours ago"],
  "_T0030": ["{0}小时后", "{0} hours later"],
  "_T0031": ["{0}分钟前", "{0} minutes ago"],
  "_T0032": ["{0}分钟后", "{0} minutes later"],
  "_T0033": ["{0}秒前", "{0} seconds ago"],
  "_T0034": ["{0}秒后", "{0} seconds later"],
  "_T0035": ["刚刚", "just now"],
  "_T0036": ["首页", "Home"],
  "_T0037": ["隐藏/显示菜单", "hide/show menu"],
  "_T0038": ["姓名", "Full Name"],
  "_T0039": ["邮箱", "Email"],
  "_T0040": ["电话", "Tel"],
  "_T0041": ["手机", "MP"],
  "_T0042": ["修改密码", "Reset PWD"],
  "_T0043": ["绑定地址", "Bind IP"],
  "_T0044": ["登录日期", "Last Login"],
  "_T0045": ["账号信息", "Account Info"],
  "_T0046": ["消息中心", "Message Center"],
  "_T0047": ["已读", "Read"],
  "_T0048": ["未读", "Unread"],
  "_T0049": ["我收到的", "I receive"],
  "_T0050": ["我发送的", "I send"],
  "_T0051": ["选择标签", "Select label"],
  "_T0052": ["批量已读", "Batch read"],
  "_T0053": ["发送给", "To: "],
  "_T0054": ["抄送给", "Cc: "],
  "_T0055": ["所有组", "All Group"],
  "_T0056": ["添加附件", "Add attachments"],
  "_T0057": ["文件上传成功（极速上传）", "File upload successful (speed upload)"],
  "_T0058": ["文件上传成功（普通上传）", "File upload successful (normal upload)"],
  "_T0059": ["新建消息", "New Message"],
  "_T0060": ["下面是引用的内容，如不需要请手动删除", "The following is the referenced content. Please delete it manually if it is not necessary"],
  "_T0061": ["来自 {0} 的消息", "Message from {0}"],
  "_T0062": ["搜索", "Search"],
  "_T0063": ["广播", "Broadcast"],
  "_T0064": ["全选", "SelectAll"],
  "_T0065": ["请输入角色名或账号名", "Please enter the role name or user name"],
  "_T0066": ["添加角色", "Add Role"],
  "_T0067": ["添加账号", "Add User"],
  "_T0068": ["权限查询", "Auth Query"],
  "_T0069": ["添加账号必须指定一个模块", "A module must be specified to add an account"],
  "_T0070": ["请输入完整账号名", "Please enter the full account name"],
  "_T0071": ["请输入菜单名或模块名", "Please enter the menu name or module name"],
  "_T0072": ["展开层级数", "Expanded num"],
  "_T0073": ["显示原始值", "Show Raw"],
  "_T0074": ["有权限的", "Y Perm"],
  "_T0075": ["无权限的", "N Perm"],
  "_T0076": ["[ 全选/反选 ]", "[ SelectAll/Reverse ]"],
  "_T0077": ["请输入权限名", "Please input perm name"],
  "_T0078": ["添加权限", "AddPerm"],
  "_T0079": ["保存权限", "SavePerm"],
  "_T0080": ["禁用权限", "DisablePerm"],
  "_T0081": ["保存配置", "Save Conf"],
  "_T0082": ["查看配置", "View Conf"],
  "_T0083": ["查看老权限", "View Old Perm"],
  "_T0084": ["查看新权限", "View New Perm"],
  "_T0085": ["必须指定角色或账号、模块、权限", "Role or account, module and perm must be specified"],
  "_T0086": ["全部", "All"],
  "_T0087": ["启用", "Enable"],
  "_T0088": ["您已下线！请将相关数据保存至记事本后重新登录", "You are offline! Please save relevant data to Notepad and log in again"],
  "_T0089": ["详细", "Detail"],
  "_T0090": ["详细列表", "Relation lists"],
  "_T0091": ["工具列表", "Tool lists"],
  "_T0092": ["查询列表", "Search lists"],
  "_T0093": ["所有显示列表", "All display lists"],
  "_T0094": ["默认显示列表", "Default display lists"],
  "_T0095": ["子表显示列表", "Sub display lists"],
  "_T0096": ["编辑状态列表", "Edit status list"],
  "_T0097": ["审核状态列表", "Verify status list"],
  "_T0098": ["显示", "Display"],
  "_T0099": ["重置", "Reset"],
  "_T0100": ["添加", "Add"],
  "_T0101": ["编辑", "Edit"],
  "_T0102": ["审核", "Verify"],
  "_T0103": ["帮助", "Help"],
  "_T0104": ["说明", "Explain"],
  "_T0105": ["工具", "Tools"],
  "_T0106": ["隐藏高级搜索", "Hide Advanced Search"],
  "_T0107": ["显示高级搜索", "Show Advanced Search"],
  "_T0108": ["高级搜索", "Advanced Search"],
  "_T0109": ["限制浏览前{0}条数据", "Restrict browsing of the first {0} data"],
  "_T0110": ["保存后继续新增", "Continue adding after saving"],
  "_T0111": ["通知", "Notice"],
  "_T0112": ["未做任何改变，是否已经提交过或未修改数据？", "No changes have been made. Has the data been submitted or not modified ?"],
  "_T0113": ["这意味着数据有效，请确认是否继续？", "This means that the data is valid. Are you sure you want to continue?"],
  "_T0114": ["当前选择的角色（点击下方选项可更改）：", "Currently selected roles(Click the option below to change):"],
  "_T0115": ["批量审核时数据状态必须一致", "Data status must be consistent during batch approval"],
  "_T0116": ["操作", "Action"],
  "_T0117": ["当前流程需要你指定一个角色", "The current process requires you to specify a role"],
  "_T0118": ["输入关键字进行过滤", "Enter keywords to filter"],
  "_T0119": ["待办事项", "ToDo List"],
  "_T0120": ["日程管理", "Schedule manage"],
  "_T0121": ["上一年", "Prev Year"],
  "_T0122": ["上个月", "Prev Month"],
  "_T0123": ["今天", "Today"],
  "_T0124": ["下个月", "Next Month"],
  "_T0125": ["下一年", "Next Year"],
  "_T0126": ["请选择工作表", "Please select a worksheet"],
  "_T0127": ["工作表", "Worksheet"],
  "_T0128": ["计算", "Calculate"],
  "_T0129": ["精度", "Precision"],
  "_T0130": ["表达式", "Expression"],
  "_T0131": ["【$+序号】表示字段，例如：($1 + $2 - $3) * 2 / 3 + $0", "[$+ sequence number] indicates a field, for example: ($1 + $2 - $3) * 2 / 3 + $0"],
  "_T0132": ["请至少勾选一项以进行删除", "Please check at least one item to delete"],
  "_T0133": ["显示详细内容", "Show Detail"],
  "_T0134": ["开始导入", "Start imp"],
  "_T0135": ["第一行必须是表头，且数据至少需要一行", "The first line must be the header, and the data needs at least one line"],
  "_T0136": ["将文件拖到此处，或<em>点击上传</em>", "Drag the file here or <em> click upload</em>"],
  "_T0137": ["批量格式化", "Batch Format"],
  "_T0138": ["一次最多批量格式化{0}条，请提前筛选需要格式化的数据", "You can format {0} rows in batch at a time. Please filter the data to be formatted in advance"],
  "_T0139": ["导出", "Export"],
  "_T0140": ["配置默认流程", "Configure default process"],
  "_T0141": ["折叠 | 展开", "Collapse | Expand"],
  "_T0142": ["求和：", "Sum: "],
  "_T0143": ["平均：", "Avg: "],
  "_T0144": ["账号模板", "Account Template"],
  "_T0145": ["正文模板", "Content Template"],
  "_T0146": ["保存搜索条件", "Save Search Condition"],
  "_T0147": ["选择搜索条件", "Select Search Condition"],
  "_T0148": ["指定条件名称", "Specify condition name"],
  "_T0149": ["消息标签（多个使用【,】分隔）", "Message labels (multiple are separated by [,])"],
  "_T0150": ["未配置收信人", "No recipient configured"],

  "_T1000": ["", ""]
} as { [key: string]: Array<string> }